

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
  namespace: default
  labels:
    app: kuberneteth
    name: monitor-config
    io.kompose.service: monitor
data:
  app.json: |-
    [
      
      {
        "name"              : "miner01",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "miner01--jsonrpc",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "miner01",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "123",
          "VERBOSITY"       : 3
        }
      },
      
      {
        "name"              : "miner02",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "miner02--jsonrpc",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "miner02",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "123",
          "VERBOSITY"       : 3
        }
      },
      
      {
        "name"              : "miner03",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "miner03--jsonrpc",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "miner03",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "123",
          "VERBOSITY"       : 3
        }
      },
      
       
      {
        "name"              : "fullnode01",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "fullnode01--jsonrpc",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "fullnode01",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "123",
          "VERBOSITY"       : 3
        }
      }
      
    ]
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: monitor-svc
  labels:
    app: kuberneteth
    tier: frontend
    name: monitor-svc
    io.kompose.service: monitor
spec:
  selector:
    app: kuberneteth
    tier: frontend

  type: NodePort
  ports:
    - protocol: TCP
      port: 3001

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: monitor
spec:
  selector:
    matchLabels:
      app: kuberneteth
  replicas: 1
  serviceName: monitor
  template:
    metadata:
      name: monitor
      labels:
        app: kuberneteth
        tier: frontend
        name: monitor
        io.kompose.service: monitor
    spec:
      initContainers:
      - name: monitor-init-container
        image: ijsfd/eth-netstats
        imagePullPolicy: IfNotPresent
        command: [ "sh" ]
        args:
        - "-cx"
        - "cp -r /eth-net-intelligence-api/* /ethmonitor;
           cp /monitor-configmap/app.json /ethmonitor/app.json;
           
           sed -i \"s/miner01--jsonrpc/$MINER01_SVC_SERVICE_HOST/g\" /ethmonitor/app.json;
           
           sed -i \"s/miner02--jsonrpc/$MINER02_SVC_SERVICE_HOST/g\" /ethmonitor/app.json;
           
           sed -i \"s/miner03--jsonrpc/$MINER03_SVC_SERVICE_HOST/g\" /ethmonitor/app.json;
           
           
           sed -i \"s/fullnode01--jsonrpc/$FULLNODE01_SVC_SERVICE_HOST/g\" /ethmonitor/app.json;
           
           exit 0;"
        volumeMounts:
        - name: monitor-configmap-volume
          mountPath: /monitor-configmap/app.json
          subPath: app.json
        - name: monitor-config-persistent-storage
          mountPath: /ethmonitor
      containers:
      - name: eth-netstats-container
        image: ijsfd/eth-netstats
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
        env:
        - name: WS_SECRET
          value: "123"
        - name: PORT
          value: "3001"
      - name: eth-net-intelligence-api-container
        image: ijsfd/eth-net-intelligence-api
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: monitor-config-persistent-storage
          mountPath: /eth-net-intelligence-api/app.json
          subPath: app.json
      volumes:
      - name: monitor-configmap-volume
        configMap:
          name: monitor-config
          items:
          - key: app.json
            path: app.json
      - name: monitor-config-persistent-storage
        persistentVolumeClaim:
          claimName: volume-ethmonitor
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: monitor.localhost
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: monitor-svc
            port:
              number: 3001

