[Eth]
NetworkId = 600
SyncMode = "full"
LightPeers = 100
DatabaseCache = 768
EnablePreimageRecording = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "/root/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Node]
UserIdent = "bootnode00"
DataDir = "/etc/testnet/bootnode"
IPCPath = "/etc/testnet/bootnode/geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["db", "eth", "net", "web3", "personal", "miner", "admin", "clique"]
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false

BootstrapNodes = []
BootstrapNodesV5 = []

StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false